### ISSUE TITLE
spawn makensis ENOENT on release-windows task

### ISSUE THREAD

**Issue by Splact** [arvindr21/slush-electron#1]
When I execute gulp release (I'm on windows) the only result is a "spawn makensis ENOENT" error.

This is the entire trace:

Error: spawn makensis ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by geolyth** [comment]
You need to install NSIS (Nullsoft Scriptable Install System), an opensource system to create Windows installers. It can be found at http://sourceforge.net/projects/nsis/
